AWSTemplateFormatVersion: '2010-09-09'
Description: |
  [Main Root Stack] Beaver Team - KT Cloud Infra 5 (Nested Stacks with Isolated UserData)
  - Objective: Prevent server downtime during traffic spikes.
  - Architecture: Multi-AZ 4-Subnets, t3.micro Compute, Separated Shell Script via S3.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Select your existing SSH KeyPair to deploy compute layers"

Resources:
  # ==========================================
  # 1-Beaver-vpc-network.yaml
  # ==========================================
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # TemplateURL에 S3 [객체 URL].
      TemplateURL: "https://beaber-infra-bucket-2026.s3.ap-northeast-2.amazonaws.com/1-beaver-vpc-network.yaml"
      
  # ==========================================
  # 2-beaver-ec2-compute.yaml
  # ==========================================
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # TemplateURL에 S3 [객체 URL].
      TemplateURL: "https://beaber-infra-bucket-2026.s3.ap-northeast-2.amazonaws.com/2-beaver-ec2-compute.yaml"
      Parameters:
        ParentVpcId: !GetAtt NetworkStack.Outputs.VpcId
        ParentPubSubnet1: !GetAtt NetworkStack.Outputs.PubSubnet1Id
        ParentPvtSubnet1: !GetAtt NetworkStack.Outputs.PvtSubnet1Id
        KeyName: !Ref KeyName